name: EasyResidenceManage
version: 1.0.0
main: pers.zhangyang.easyresidencemanage.EasyResidenceManage
api-version: 1.13
commands:
  EasyResidenceManage:
    aliases: erm
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints