name: EasyResidenceManager
version: 1.1.2
main: pers.zhangyang.easyresidencemanager.EasyResidenceManager
api-version: 1.13
commands:
  EasyResidenceManager:
    aliases: erm
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints